### ISSUE TITLE
How do you add background services?

### ISSUE THREAD

**Issue by robertchoi** [NordicSemiconductor/Android-nRF-Blinky#49]
The current source goes to the background, and it does not work.

What should I do to add a service so that I can notify you when the application receives a button event in the background?

**Comment by philips77** [comment]
Hi @robertchoi,
In the current implementation of nRF Blinky the service is held in View Model. This is to make the app simple. To make it work when the app goes to background, you should consider using a `Service` instead, and promote it to foreground so that it doesn't get killed by the system on Android Oreo+. We have such example in nRF Toolbox app: https://github.com/NordicSemiconductor/Android-nRF-Toolbox/tree/master/app/src/main/java/no/nordicsemi/android/nrftoolbox/csc
A foreground service always displays a notification to the user showing that a service in bg is running. You may give it a label indicating a connected device and perhaps add some buttons, e.g. (in case of LED Button service) to turn on the LED.
